#!/usr/bin/env ruby

require "json"
require "net/http"
require "time"
require "uri"
require "yaml"

DATA_DIR = File.expand_path(__dir__)
INPUT_FILE = File.join(DATA_DIR, "resources.yml")
OUTPUT_FILE = File.join(DATA_DIR, "resources_github.yml")
API_ROOT = "https://api.github.com"
DEFAULT_ORGS = ["COMBINE-lab"].freeze
MIN_DISCOVERED_REPOS = ENV.fetch("RESOURCE_MIN_DISCOVERED_REPOS", "50").to_i

class GitHubApiError < StandardError; end
class GitHubRateLimitError < GitHubApiError; end

def inventory_orgs
  ENV.fetch("RESOURCE_GITHUB_ORGS", DEFAULT_ORGS.join(","))
     .split(",")
     .map(&:strip)
     .reject(&:empty?)
end

def github_get(path)
  uri = URI("#{API_ROOT}#{path}")
  request = Net::HTTP::Get.new(uri)
  request["Accept"] = "application/vnd.github+json"
  request["User-Agent"] = "combine-lab.github.io resource metadata builder"
  request["X-GitHub-Api-Version"] = "2022-11-28"
  request["Authorization"] = "Bearer #{ENV["GITHUB_TOKEN"]}" if ENV["GITHUB_TOKEN"]

  response = Net::HTTP.start(uri.hostname, uri.port, use_ssl: true) do |http|
    http.request(request)
  end

  return nil if response.code == "404"

  unless response.is_a?(Net::HTTPSuccess)
    message = "GitHub API request failed for #{path}: #{response.code} #{response.message}"
    if ["403", "429"].include?(response.code)
      raise GitHubRateLimitError, message
    end

    raise GitHubApiError, message
  end

  JSON.parse(response.body)
end

def github_get_pages(path)
  page = 1
  records = []

  loop do
    separator = path.include?("?") ? "&" : "?"
    response = github_get("#{path}#{separator}per_page=100&page=#{page}")
    break unless response&.any?

    records.concat(response)
    break if response.length < 100

    page += 1
  end

  records
end

def repo_metadata(repo, curated_repos, details = nil)
  details ||= github_get("/repos/#{repo}")
  unless details
    warn "Skipping #{repo}; repository metadata could not be fetched."
    return nil
  end

  repo_key = details["full_name"].downcase
  display_repo = curated_repos.fetch(repo_key, details["full_name"])
  release = curated_repos.key?(repo_key) ? github_get("/repos/#{details["full_name"]}/releases/latest") : nil

  {
    "repo" => display_repo,
    "name" => details["name"],
    "full_name" => details["full_name"],
    "description" => details["description"],
    "html_url" => details["html_url"],
    "homepage" => details["homepage"],
    "language" => details["language"],
    "topics" => details["topics"] || [],
    "stargazers_count" => details["stargazers_count"],
    "forks_count" => details["forks_count"],
    "open_issues_count" => details["open_issues_count"],
    "fork" => details["fork"],
    "archived" => details["archived"],
    "pushed_at" => details["pushed_at"],
    "latest_release" => release&.fetch("tag_name", nil),
    "latest_release_url" => release&.fetch("html_url", nil),
    "curated" => curated_repos.key?(repo_key),
    "generated_at" => Time.now.utc.iso8601
  }.reject { |_key, value| value.nil? }
end

begin
resources = YAML.load_file(INPUT_FILE)
curated_repos = resources.each_with_object({}) do |resource, repos|
  repo = resource["repo"]
  repos[repo.downcase] = repo if repo
end

discovered_repo_details = inventory_orgs.flat_map do |org|
  github_get_pages("/orgs/#{org}/repos?type=public")
    .reject { |repo| repo["fork"] }
end

if discovered_repo_details.length < MIN_DISCOVERED_REPOS
  raise GitHubApiError,
        "Only discovered #{discovered_repo_details.length} public non-fork org repos. " \
        "Expected at least #{MIN_DISCOVERED_REPOS}; refusing to write partial metadata."
end

discovered_by_repo = discovered_repo_details.each_with_object({}) do |details, repos|
  repos[details["full_name"].downcase] = details
end

all_repos = (curated_repos.values + discovered_by_repo.keys).uniq { |repo| repo.downcase }

generated = all_repos.map do |repo|
  repo_metadata(repo, curated_repos, discovered_by_repo[repo.downcase])
end.compact
generated = generated.sort_by { |resource| [resource["curated"] ? 0 : 1, resource["repo"].downcase] }

File.write(
  OUTPUT_FILE,
  "# Generated by _data/build-resources.rb. Do not edit by hand.\n\n#{generated.to_yaml}"
)

puts "Wrote #{generated.length} resource metadata records to #{OUTPUT_FILE}"
puts "  curated: #{generated.count { |resource| resource["curated"] }}"
puts "  discovered public non-fork repos: #{generated.count { |resource| !resource["curated"] }}"
rescue GitHubApiError => error
  warn error.message
  warn "Resource metadata was not updated."
  exit 1
end
